; configuration for all machines 
[all:vars]
ansible_user=ponch
ansible_ssh_private_key_file=/home/ponch/.ssh/id_ed25519
[test-server]
server1 ansible_host=34.173.19.201
[prod-server]
server2 ansible_host=34.96.205.196